version: "3.3"

services:
  postgres:
    image: "postgres:15-alpine"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-annoplot}
      POSTGRES_USER: ${POSTGRES_USER:-annoplotuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-annoplot123}
    ports:
      - "${POSTGRES_EXPOSED:-5432}:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    networks:
      - anno_plot_network

  annoplot-backend-api:
    image: uhhlt/anno_plot_backend:latest
    command: /anno_plot_code/src/backend_api_entrypoint.sh
    user: ${UID:-1000}:${GID:-1000}
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DB:-annoplot}
      POSTGRES_USER: ${POSTGRES_USER:-annoplotuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-annoplot123}
      LOG_LEVEL: ${LOG_LEVEL:-info}
      API_PORT: ${API_PORT:-5500}
      API_PRODUCTION_MODE: ${API_PRODUCTION_MODE:-0}
      API_PRODUCTION_WORKERS: ${API_PRODUCTION_WORKERS:-10}
      NUMBA_CACHE_DIR: /tmp
      HUGGINGFACE_HUB_CACHE: /models_cache
      TRANSFORMERS_CACHE: /models_cache
    volumes:
      - ../backend/src:/anno_plot_code/src
      - ./exported:/anno_plot_code/exported
      - ./models_cache:/models_cache
    depends_on:
      - postgres
    ports:
      - "${BACKEND_EXPOSED:-5500}:${API_PORT}"
    restart: always
    links:
      - postgres
    networks:
      - anno_plot_network
    profiles:
      - backend

  annoplot-frontend:
    image: uhhlt/anno_plot_frontend:latest
    depends_on:
      - annoplot-backend-api
    ports:
      - "${FRONTEND_EXPOSED:-3000}:3000"
    networks:
      - anno_plot_network
    profiles:
      - frontend

volumes:
  postgres_data:
    driver: local

networks:
  anno_plot_network:
